version: '3.4'

services:
  todoserver:
    image: ${DOCKER_REGISTRY-}todoserver
    build:
      context: .
      dockerfile: TodoServer/Dockerfile
    ports:
      - "3000:80"
  redis:
    image: redis
    container_name: cache
    ports:
      - "6379:6379"